#!/bin/bash
#------------------------------------------------------------==ADM==
# Custom Software, Developed for CUHEP by staff.
# This software is in the public domain, furnished "as is", without
# technical support, and with no warranty, express or implied, as
# to its usefulness for any purpose.
#
# MakeListFiles      
#
# REVISION HISTORY
# Created.                                  04/25/2018  doug johnson
#-------------------------------------------------------------------

count=1
inputFile=${1:-TestInput.lst}
outputFile=${2:-TestOutput.lst}

cat /dev/null > $outputFile
cat /dev/null > $inputFile

for file in $(ls inputs/*); do
   echo `date`" Adding $file to $inputFile and output/count${count}.dat to $outputFile"
   echo -n "output/count${count}.dat, " >> $outputFile
   base=`basename $file`
   echo "$file, -f $base  -o output.dat" >> $inputFile
   ((count++))
done
echo " " >> $outputFile

