#!/usr/bin/python
import argparse
import sys
from collections import Counter
import re

global outFile, inFile
parser = argparse.ArgumentParser(description='Process some integers.')

parser.add_argument("-f", "--file", dest="filename",
                    help="write report to FILE", metavar="FILE")
parser.add_argument("-o", "--output", dest="output",
                    help="write report to FILE", metavar="FILE")
args = parser.parse_args()

filename = args.filename
output   = args.output
file = open(filename, "r")
output= open(output,"w")

output.write("   %s\n" % (filename))

words = re.findall(r'\w+', open(filename).read().lower())
for item in Counter(words).most_common(100): 
    if len(item[0]) >= 4:
#        print("{}\t{}".format(*item)) 
        output.write("%-10s    %8d\n" % (item[0], item[1]))

output.close()

sys.exit(0)
