#!/usr/bin/python

import argparse
import sys
from collections import Counter
import re
import time
import random

parser = argparse.ArgumentParser(description='Process some integers.')

parser.add_argument("-f", "--file", dest="filename",
                    help="write report to FILE", metavar="FILE")
args = parser.parse_args()

filename = args.filename
print "  " + filename

words = re.findall(r'\w+', open("inputs/" + filename).read().lower())
for item in Counter(words).most_common(100): 
    if len(item[0]) >= 4:
        print("{}\t{}".format(*item)) 

time.sleep(random.randint(5, 20))
sys.exit(0)
